#include "CReferee.hpp"
#include "CGame.hpp"
#include "CReader.hpp"
#include "CFWriter.hpp"
#include "CGWriter.hpp"
#include "CRWriter.hpp"
#include <iostream>
#include <string>
#include <time.h>
#include <stdlib.h>