#include "CReferee.hpp"
#include "CGame.hpp"
#include "CReader.hpp"
#include "CFWriter.hpp"
#include "CGWriter.hpp"
#include "CRWriter.hpp"
#include "CRManager.hpp"
#include "CGManager.hpp"
#include "CCenterCalculator.hpp"
#include "CAssistantCalculator.hpp"
#include <iostream>
#include <string>
#include <stdlib.h>